### ISSUE TITLE
Update the instructions to build the docs in here. https://github.com/NVIDIA-Merlin/systems/tree/main/docs

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/systems#73] opened 2022-03-31 23:18 UTC

**Comment by viswa-nvidia** [comment] 2022-03-31 23:20
Assigning this to you for now. Please assign to the relevant person

**Comment by karlhigley** [comment] 2022-04-01 03:01
Duplicate of #68

**Closed by karlhigley** 2022-04-01 03:01 UTC
