### ISSUE TITLE
[BUG] getting error when serving 0_transformworkflowtriton in session-based example

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/systems#360] opened 2023-06-05 20:07 UTC
### Bug description

I am getting the following error when serving `0_transformworkflowtriton`. The error occurs when I send a request to the server:

```
Failed to transform operator <merlin.dag.ops.udf.UDF object at 0x7f3abb31d970>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 4240, in _ensure_valid_index
    value = Series(value)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/series.py", line 436, in __init__
    data, index = self._init_dict(data, index, dtype)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/series.py", line 511, in _init_dict
    if data:
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/single_column_frame.py", line 95, in __bool__
    raise TypeError(
TypeError: The truth value of a <class 'cudf.core.series.Series'> is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/merlin/dag/executors.py", line 214, in _run_node_transform
    transformed_data = node.op.transform(selection, input_data)
  File "/usr/local/lib/python3.8/dist-packages/merlin/dag/ops/udf.py", line 77, in transform
    new_df[col] = self.f(transformable[col])
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3978, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 4172, in _set_item
    value = self._sanitize_column(value)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 4902, in _sanitize_column
    self._ensure_valid_index(value)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 4242, in _ensure_valid_index
    raise ValueError(
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

```

### Steps/Code to reproduce bug

1. Please run the notebooks `1`  and `2` in this [folder](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/end-to-end-session-based):
2. Launch triton server
3. Send the request to triton server as follows:
```
col_names = ['product_recency_days_log_norm-list__values', 'product_recency_days_log_norm-list__offsets', 'et_dayofweek_sin-list__values', 'et_dayofweek_sin-list__offsets', 'item_id-list__values', 'item_id-list__offsets', 'category-list__values', 'category-list__offsets']
response = send_triton_request(workflow.input_schema, filtered_batch, col_names, triton_model='0_transformworkflowtriton')
print(response)
```

### Environment details

- Merlin version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):

### Additional context

I am using `merlin-pytorch:23.04` image with all the latest main branches pulled and dependencies installed.

**Comment by viswa-nvidia** [comment] 2023-06-06 17:54
@jperez999 , @oliverholworthy  This needs to be added as a unit test in core. This is related to the move of lambda ops in core.

**Comment by viswa-nvidia** [comment] 2023-06-06 17:55
@rnyak , to help with the reproducer

**Comment by jperez999** [comment] 2023-06-08 13:15
This problem is understood it happens because the input to the lambda is a pandas dataframe and we are creating cudf series. After running a column through the lambda we try to set it back to a pandas dataframe (same type as input) and that is where the failure occurs.

**Comment by rnyak** [comment] 2023-06-08 13:42
> @rnyak , to help with the reproducer

repro was provided to Julio.

**Comment by jperez999** [comment] 2023-06-08 17:13
Fix is in the core repo https://github.com/NVIDIA-Merlin/core/pull/342

**Closed** 2023-06-09 12:54 UTC
Labels: bug, P0
